//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPDOTHE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAPDOTHE()
        {
            this.LOAIKHACHHANGs = new HashSet<LOAIKHACHHANG>();
            this.THETHANHVIENs = new HashSet<THETHANHVIEN>();
        }
    
        public int MACD { get; set; }
        public int MALKH { get; set; }
        public string TENCD { get; set; }
        public Nullable<decimal> DIEMCD { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        public virtual LOAIKHACHHANG LOAIKHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAIKHACHHANG> LOAIKHACHHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THETHANHVIEN> THETHANHVIENs { get; set; }
    }
}
