//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIADICHVU
    {
        public int MADGDV { get; set; }
        public Nullable<System.DateTime> NGAYDGDV { get; set; }
        public Nullable<int> MAMUC { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MALDV { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAIDICHVU LOAIDICHVU { get; set; }
        public virtual MUCDOHAILONG MUCDOHAILONG { get; set; }
    }
}
