//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHTHUCTANGKEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HINHTHUCTANGKEM()
        {
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public int MAHTTK { get; set; }
        public Nullable<int> MALSP { get; set; }
        public string TENHTTK { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string MOTA { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
    }
}
