//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public int MAKM { get; set; }
        public string TENKM { get; set; }
        public Nullable<int> MALKH { get; set; }
        public Nullable<int> MAHTTK { get; set; }
        public Nullable<int> MAHTVC { get; set; }
        public Nullable<int> MAHTGG { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string MOTA { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual HINHTHUCGIAMGIA HINHTHUCGIAMGIA { get; set; }
        public virtual HINHTHUCTANGKEM HINHTHUCTANGKEM { get; set; }
        public virtual HINHTHUCVOUCHER HINHTHUCVOUCHER { get; set; }
        public virtual LOAIKHACHHANG LOAIKHACHHANG { get; set; }
    }
}
