//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SqlProviderServices = System.Data.Entity.SqlServer.SqlProviderServices;

    public partial class QuanLyKhuyenMaiEntities : DbContext
    {
        public QuanLyKhuyenMaiEntities()
            : base("name=QuanLyKhuyenMaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAPDOTHE> CAPDOTHEs { get; set; }
        public virtual DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHITIETSANPHAMTANGKEM> CHITIETSANPHAMTANGKEMs { get; set; }
        public virtual DbSet<DANHGIADICHVU> DANHGIADICHVUs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<HINHTHUCGIAMGIA> HINHTHUCGIAMGIAs { get; set; }
        public virtual DbSet<HINHTHUCTANGKEM> HINHTHUCTANGKEMs { get; set; }
        public virtual DbSet<HINHTHUCVOUCHER> HINHTHUCVOUCHERs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAIDICHVU> LOAIDICHVUs { get; set; }
        public virtual DbSet<LOAIKHACHHANG> LOAIKHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<MUCDOHAILONG> MUCDOHAILONGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THETHANHVIEN> THETHANHVIENs { get; set; }
    }
}
