//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class THETHANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THETHANHVIEN()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public int MATHE { get; set; }
        public Nullable<int> DIEM { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public bool TINHTRANG { get; set; }
        public int MACD { get; set; }
    
        public virtual CAPDOTHE CAPDOTHE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
